packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.13.6
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/zod': ^1.12.2
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  next: ^16.1.1
  typescript: ^5
  zod: 4.3.5
